added collection call options for 3.6 compatibility
mongomock/mongomock pull request #393
Opened 2018-05-28 08:30 UTC by gpernot

Just add bypass_document_validation= and session= options to collection calls for 3.6 compatibility

2018-05-28 09:15 UTC, vmalloc requested changes

2018-05-28 09:15 UTC, vmalloc commented on mongomock/collection.py
> +    def update_one(self, filter, update, upsert=False, bypass_document_validation=False,
what's array_filters? does it have noticeable side effects when used?

2018-05-28 09:44 UTC, gpernot commented
Hi,

> 
> - def update_one(self, filter, update, upsert=False):
> + def update_one(self, filter, update, upsert=False, bypass_document_validation=False,what's
> array_filters? does it have noticeable side effects when used?

actually, it does have side effects : it updates array elements matching the filters.
https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/#up._S_[%3Cidentifier%3E]

i have no clue on how to implement this is mongomock, maybe we should just drop the array_filters parameter for now ?

2018-06-03 06:23 UTC, vmalloc commented
@gpernot yes - if you can't provide a matching implementation it's better to not support it at all, as per the guidelines

2018-06-04 08:59 UTC, gpernot reviewed
I only left the 'session' parameter in latest patch. I guess the implementation is fine, as mongomock is basically synchronous.

2018-06-04 10:48 UTC, vmalloc approved these changes

2018-06-11 05:53 UTC, vmalloc commented
@gpernot I can't merge this since the Travis build is failing. Can you take a look?

2018-06-11 07:48 UTC, gpernot commented
11 juin 2018 07:54 "Rotem Yaari" <notifications@github.com> a écrit:
> @gpernot I can't merge this since the Travis build is failing. Can you take a look?

travis fails on :
./mongomock/__init__.py:79:1: E402 module level import not at top of file

and i haven't modified __init__.py at all

maybe you have more experience than me on this ?

2018-06-11 10:07 UTC, vmalloc commented
Ok, will take a look. Likely I'll have to ask you to rebase on develop in case I need to fix anything.

2018-06-11 10:34 UTC, vmalloc commented
@gpernot I fixed the flake8 settings on develop. Can you please rebase?

2018-06-11 13:44 UTC, merged

2018-06-11 13:44 UTC, vmalloc commented
Thanks!