Consider "name" argument to create_index for index name
mongomock/mongomock pull request #550
Opened 2019-07-22 08:10 UTC by rbu

Current version does not allow giving a human readable index name.

2019-07-26 16:59 UTC, schizef commented
Thanks for the PR, I also need this!  However, it looks like `create_indexes` probably needs `name` added as well.

2019-07-27 22:34 UTC, pcorpet requested changes
Yes indeed, please add name in `create_indexes` before I merge.

2019-07-29 10:13 UTC, rbu commented
> Yes indeed, please add name in `create_indexes` before I merge.

Thank you for the review. I've implemented this change as proposed.

2019-07-29 11:42 UTC, pcorpet approved these changes

2019-07-29 11:43 UTC, merged