Type conversion
mongomock/mongomock pull request #583
Opened 2020-01-06 15:23 UTC by creek0810

add type conversion operation
- toString
- toInt

2020-01-07 23:11 UTC, pcorpet requested changes
Thanks for your work. Please also add a test in test__mongomock to compare with pymongo behaviour.

2020-01-07 23:11 UTC, pcorpet commented on tests/test__collection_api.py
> +        collection.insert_many([
insert_one should be enough here

2020-01-07 23:11 UTC, pcorpet commented on tests/test__collection_api.py
> +        collection.insert_many([
Same here

2020-01-07 23:11 UTC, pcorpet commented on tests/test__collection_api.py
> +        actual = collection.aggregate(
Same here

2020-01-08 03:05 UTC, creek0810 commented on tests/test__collection_api.py
> +        collection.insert_many([
Done

2020-01-08 03:06 UTC, creek0810 commented
I have add test in test__mongomock and change insert_many to insert_many.

2020-01-14 16:43 UTC, pcorpet approved these changes

2020-01-14 16:43 UTC, merged