Support for $slice operator in projection argument
mongomock/mongomock pull request #588
Opened 2020-01-21 23:16 UTC by kdeyev

Hi,

I've added support for lists slicing in the projection argument. Like that:
find({'name': 'Array'}, projection={'name': 1, 'values': {'$slice': [-3, 10]}}

Please, review and approve :-)

2020-01-27 13:48 UTC, pcorpet requested changes

2020-01-27 13:48 UTC, pcorpet commented on mongomock/collection.py
> +                    raise OperationFailure(
I suggest you reverse your if so that you can raise and avoid an `else` branch:
```py
if not is instance(doc_copy[field], list):
  raise ...
op_value = op['$slice']
```

2020-01-27 13:48 UTC, pcorpet commented on mongomock/collection.py
> +                        skip = op_value[0]
```py
skip, limit = op_value
```

2020-01-27 13:48 UTC, pcorpet commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_num_slice(self):
Please move those tests to test__collection_api as the compare object actually does two operations (one on a real Mongo DB, the other on a mongomock) but the exception would raise only for the first one, thus it's not testing what you wish. I'll work on a way to make that easier.

2020-01-27 13:48 UTC, pcorpet commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_num_slice(self):
OK done. Rebase then use `self.cmp.compare_exceptions.find({'name': ...`

2020-01-28 03:22 UTC, kdeyev commented on mongomock/collection.py
> +                    raise OperationFailure(
Done

2020-01-28 03:22 UTC, kdeyev commented on mongomock/collection.py
> +                    raise OperationFailure(
Done

2020-01-28 03:28 UTC, kdeyev commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_num_slice(self):
I've started to use `compare_exceptions` method. Thank you!
I looked at test__collection_api file and I see that no one of tests is using `MultiCollection` for comparison of results. Actually it means that moving of new tests will require to bring some additional code to the `test__collection_api` (such as `_CollectionComparisonTest` for example). 
Please let me know if you want me anyway moving the new tests into `test__collection_api`

2020-01-28 03:29 UTC, kdeyev commented on mongomock/collection.py
> +                        skip = op_value[0]
Done

2020-01-28 03:32 UTC, kdeyev reviewed
Thank you for reviewing my PR. 
I've followed the CR comments. Please review the new commits.

2020-01-28 08:19 UTC, pcorpet commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_num_slice(self):
Nope, it's OK now that we have `compare_exceptions`.

2020-01-28 08:23 UTC, pcorpet requested changes
Thanks for all the change. It's almost good to go.

2020-01-28 08:23 UTC, pcorpet commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_value_type(self):
Please add one last test with a `slice` using neither a list nor an int: `{'name': 1, 'values': {'$slice': '3'}}`

2020-01-28 13:11 UTC, kdeyev reviewed
One more test was added. Please, approve.

2020-01-28 13:11 UTC, kdeyev commented on tests/test__mongomock.py
> +    def test__projection_slice_list_wrong_value_type(self):
Done

2020-01-28 13:14 UTC, pcorpet approved these changes

2020-01-28 13:14 UTC, merged

2020-01-28 13:14 UTC, pcorpet commented
Thanks for the very clean result @kdeyev

2020-01-28 13:28 UTC, kdeyev commented
Thank you! If you don't mind I'll continue to add MongoDB features support.