Add support for read concern
mongomock/mongomock pull request #628
Opened 2020-05-22 14:28 UTC by abarto

Adds support for setting the read concern at the collection level restoring compatibility with mongoengine 0.20.

Fixes: https://github.com/mongomock/mongomock/issues/625

2020-05-23 06:36 UTC, pcorpet requested changes
Thanks a lot for your contribution. Please address my comments and try to fix the CI

2020-05-23 06:36 UTC, pcorpet commented on mongomock/read_concern.py
> +        if isinstance(other, ReadConcern):
Please use an equality that would work with the pymongo ReadConcern (see `write_concern` for an example)

2020-05-23 06:36 UTC, pcorpet commented on tests/test__collection_api.py
> +    def test__with_options_different_write_readconcern(self):
Please fix the name `...different_read_concern`

2020-05-23 06:36 UTC, pcorpet commented on tests/test__collection_api.py
> +        # Check that each object has its own write concern.
Update the comment here as well

2020-05-23 06:36 UTC, pcorpet commented on tests/test__collection_api.py
> +    from mongomock.read_concern import ReadConcern
Please import the real ReadConcern in the other part of the branch

2020-05-23 21:27 UTC, pcorpet approved these changes

2020-05-23 21:27 UTC, merged

2020-06-08 19:50 UTC, lsmar commented
Any plans to integrate this into a release? 3.19.1?