Add support for group by DBRefs
mongomock/mongomock pull request #636
Opened 2020-06-15 16:18 UTC by mstrotta

Fixes issue #584

2020-06-17 06:24 UTC, pcorpet requested changes
Thanks a lot for providing a PR to fix that bug. Please fix Travis and take a look at my comment.

2020-06-17 06:24 UTC, pcorpet commented on mongomock/filtering.py
> +    from bson import Regex, DBRef
`mongomock` should work even if `pymongo` is not installed. Please fix what should happen in that case.

2020-06-17 06:24 UTC, pcorpet commented on mongomock/filtering.py
> +        return 55
Thanks for adding it here as well, please make sure that the sorting of type is working as in `pymongo` by adding a line in `test__sort_mixed_types` in `test__mongomock.py`

2020-06-17 06:24 UTC, pcorpet commented on tests/test__collection_api.py
> +    def test__aggregate_group_dbref_key(self):
Thanks for adding a unit test. Please also add an equivalent test in `test__mongomock.py` to ensure consistency with `pymongo` behavior.

2020-07-31 15:37 UTC, kosqx commented
Hi! Your CI build failed because of the https://github.com/mongomock/mongomock/issues/648 error.

I will push the fix soon

2020-07-31 15:54 UTC, kosqx commented
The fix is ready, tests are passing: https://github.com/mongomock/mongomock/pull/649

2020-08-01 13:59 UTC, merged