Fix aggregation failing if index does not exists
mongomock/mongomock pull request #646
Opened 2020-07-25 15:00 UTC by dvvolynkin

2020-07-25 21:31 UTC, pcorpet requested changes
Thanks for the fix.

Please add a test in test__mongomock to ensure that there are no regression and that we have the same behavior than pymongo going forward.

2020-07-26 20:13 UTC, dvvolynkin commented
Done

2020-07-30 08:11 UTC, pcorpet requested changes

2020-07-30 08:11 UTC, pcorpet commented on mongomock/aggregate.py
> +                return array[index]
What about negative values? Can you add a test for that as well please?

I guess the implementation could be easier and more pythonic with:
```py
try:
  return array[index]
except IndexError:
  raise KeyError('%s is not a valid index in array' % index)
```

2020-07-30 08:11 UTC, pcorpet commented on mongomock/aggregate.py
> +            # As I understood, this type of exception will be caught in the top
It's not slower: that's great, you can get rid of the comment

2022-02-06 17:11 UTC, pcorpet approved these changes

2022-02-06 19:14 UTC, merged

2022-02-06 19:14 UTC, pcorpet commented
Thanks Daniil