Sublist candidate handling update
mongomock/mongomock pull request #676
Opened 2020-10-27 14:30 UTC by studentofkyoto

Fix #673 

In case of array values, `NOTHING` object seemed rather ignored.

[here](https://github.com/studentofkyoto/mongomock/tree/find-on-array) is more boilerplate version just in case.

I am new to open source contribution. Please guide me through if I am doing something wrong.

2020-11-13 20:00 UTC, pcorpet requested changes
Thanks for your proposal and sorry for the delay in reviewing.

2020-11-13 20:00 UTC, pcorpet commented on tests/test__collection_api.py
> +        self.assertEqual([4, 5], [doc['_id'] for doc in results])
Please add an equivalent of those tests in test__mongomock as well to make sure the behavior is consistant with `pymongo`

2020-11-18 09:25 UTC, studentofkyoto commented on tests/test__collection_api.py
> +        self.assertEqual([4, 5], [doc['_id'] for doc in results])
OK, working on it! Thanks.

2021-03-16 02:23 UTC, studentofkyoto commented
Rebased the branch to pass CI. Terribly sorry for a whooshing half-year delay!

2021-03-29 13:35 UTC, pcorpet approved these changes

2021-03-29 13:35 UTC, pcorpet commented on tests/test__mongomock.py
> +            {'_id': 6, 'shape': {'color': ['red', 'yellow']}},
Please add another item
`{'_id': 7, 'shape': [{'color': 'red'}, {'color': None}]}`

2022-02-06 15:21 UTC, merged