add partialFilterExpression support for create_index
mongomock/mongomock pull request #696
Opened 2021-02-02 15:12 UTC by chdsbd

fixes #687

2021-03-29 13:38 UTC, pcorpet requested changes
Please fix lint errors detected by the CI.

2021-03-29 13:38 UTC, pcorpet commented on tests/test__collection_api.py
> +    def test_unique_index_partial_filter_expression(self):
Great test, can you try to add the same in test__mongomock to ensure we are consistent with `pymongo + MongoDB` please?

2021-04-01 21:51 UTC, pcorpet commented on tests/test__collection_api.py
> +    def test_unique_index_partial_filter_expression(self):
Sorry I wasn't clear enough: please add the equivalent test, in a `_CollectionComparisonTest` test suite. Calls should use `self.cmp.do` and the expectations should not the be on the actual result but that the results match between mongomock and pymongo. I hope that it's clearer.

2021-11-24 14:39 UTC, jschlyter commented
Any updates on this PR?

2022-05-31 11:43 UTC, Naushi commented
Any updates?

2022-05-31 11:56 UTC, pcorpet commented on tests/test__collection_api.py
> +    def test_unique_index_partial_filter_expression(self):
This is still unresolved

2022-05-31 11:56 UTC, pcorpet commented
There are remaining unresolved comments. @Naushi @jschlyter you can create a concurrent PR if you want to finish the cleanup.

2022-07-07 09:36 UTC, pcorpet commented
#784 was created, and I'm reviewing there. Closing this one.

2022-07-07 09:36 UTC, closed without merging